# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-02 15:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certifications', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0001_initial'),
        ('authorities', '__first__'),
        ('persons', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to=b'')),
                ('submitted_at', models.DateField(auto_now_add=True)),
                ('observations', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('summary', models.TextField()),
                ('begins', models.DateField()),
                ('finish', models.DateField()),
                ('timetable', models.TextField()),
                ('min_nbr_participants', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_nbr_participants', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('recrutation_starts', models.DateField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, b'in preparation'), (2, b'in recrutation'), (3, b'finished'), (4, b'cancelled')])),
                ('observations', models.TextField(blank=True, null=True)),
                ('accreditation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certifications.Accreditation')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Location')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_manager', to=settings.AUTH_USER_MODEL)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_authorities', to='authorities.Authority')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_profesors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=b'')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, b'didactic material'), (2, b'publicity'), (3, b'administrative')])),
                ('observations', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payed', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, b'recruited'), (2, b'participant'), (3, b'completed'), (4, b'aworded')])),
                ('observations', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateField(auto_now_add=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certifications.Certificate')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Person')),
            ],
        ),
        migrations.AddField(
            model_name='communication',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
    ]
