# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 10:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('certifications', '0001_initial'),
        ('authorities', '0001_initial'),
        ('persons', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to=b'')),
                ('sent_at', models.DateField(auto_now_add=True)),
                ('observations', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begins', models.DateField()),
                ('finish', models.DateField()),
                ('timetable', models.TextField()),
                ('min_nbr_participants', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_nbr_participants', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('recrutation_starts', models.DateField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, b'preparation'), (2, b'recrutation'), (3, b'finished'), (4, b'cancelled')], default=1)),
                ('observations', models.TextField(blank=True, null=True)),
                ('poster', models.ImageField(upload_to=b'courses/posters')),
                ('accreditation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certifications.Accreditation')),
            ],
        ),
        migrations.CreateModel(
            name='EducationalProgramme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('achivement', models.TextField()),
                ('summary', models.TextField()),
                ('programme', models.TextField()),
                ('certification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certifications.Certification')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_edu_programmes', to='authorities.Authority')),
                ('requires', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('currency', models.CharField(choices=[(b'EUR', b'Euros'), (b'DOL', b'Dollars')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=b'')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, b'didactic material'), (2, b'publicity'), (3, b'administrative')])),
                ('observations', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payed', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, b'recruited'), (2, b'participant'), (3, b'completed'), (4, b'aworded')], default=1)),
                ('observations', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateField(auto_now_add=True)),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certifications.Certificate')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Person')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='fee',
            name='participant_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.ParticipantGroup'),
        ),
        migrations.AddField(
            model_name='fee',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.EducationalProgramme'),
        ),
        migrations.AddField(
            model_name='fee',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Zone'),
        ),
        migrations.AddField(
            model_name='course',
            name='educational_programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.EducationalProgramme'),
        ),
        migrations.AddField(
            model_name='course',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Location'),
        ),
        migrations.AddField(
            model_name='course',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_managers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_organizers', to='authorities.Authority'),
        ),
        migrations.AddField(
            model_name='course',
            name='professors',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communication',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
    ]
