# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 11:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalprogramme',
            name='public',
            field=models.TextField(default=datetime.datetime(2015, 12, 11, 11, 9, 16, 651148, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='educationalprogramme',
            name='certification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certifications.CertificationProgramme'),
        ),
    ]
