# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 11:19
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_auto_20151211_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='sent_by',
            field=models.ForeignKey(default=datetime.datetime(2015, 12, 11, 11, 18, 54, 309987, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2015, 12, 11, 11, 18, 58, 533894, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(default=datetime.datetime(2015, 12, 11, 11, 19, 3, 157829, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationalprogramme',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2015, 12, 11, 11, 19, 13, 668761, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationalprogramme',
            name='created_by',
            field=models.ForeignKey(default=datetime.datetime(2015, 12, 11, 11, 19, 16, 693071, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2015, 12, 11, 11, 19, 19, 532762, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='created_by',
            field=models.ForeignKey(default=datetime.datetime(2015, 12, 11, 11, 19, 22, 356752, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='professors',
            field=models.ManyToManyField(related_name='related_professors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='educationalprogramme',
            name='public',
            field=models.TextField(help_text=b'public to which programme is directed'),
        ),
        migrations.AlterField(
            model_name='file',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.EducationalProgramme'),
        ),
    ]
