# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 10:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authorities', '0001_initial'),
        ('persons', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accreditation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('released_at', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('released_at',),
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observations', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=b'')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accreditation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certifications.Accreditation')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250, verbose_name=b'certificate title')),
                ('cert_type', models.PositiveSmallIntegerField(choices=[(1, b'Achievement'), (2, b'Aword')])),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=b'')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorities.Authority')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='certification',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certifications.Discipline'),
        ),
        migrations.AddField(
            model_name='certification',
            name='requires',
            field=models.ForeignKey(blank=True, help_text='indicates if cerfiticate\n        requires pssesion of another certificate', null=True, on_delete=django.db.models.deletion.CASCADE, to='certifications.Certification'),
        ),
        migrations.AddField(
            model_name='accreditation',
            name='certification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_acreditations', to='certifications.Certification'),
        ),
        migrations.AddField(
            model_name='accreditation',
            name='certifiers',
            field=models.ManyToManyField(related_name='related_certifiers', to='authorities.Certifier'),
        ),
        migrations.AddField(
            model_name='accreditation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accreditation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Location'),
        ),
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together=set([('person', 'accreditation')]),
        ),
    ]
