# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 11:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20151211_1109'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authorities', '0001_initial'),
        ('certifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationProgramme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250, verbose_name=b'certificate title')),
                ('cert_type', models.PositiveSmallIntegerField(choices=[(1, b'Achievement'), (2, b'Aword')])),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=b'')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorities.Authority')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certifications.Discipline')),
                ('requires', models.ForeignKey(blank=True, help_text='indicates if ather certification rograme is necessary', null=True, on_delete=django.db.models.deletion.CASCADE, to='certifications.CertificationProgramme')),
            ],
        ),
        migrations.RemoveField(
            model_name='certification',
            name='authority',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='discipline',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='requires',
        ),
        migrations.AlterField(
            model_name='accreditation',
            name='certification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_acreditations', to='certifications.CertificationProgramme'),
        ),
        migrations.DeleteModel(
            name='Certification',
        ),
    ]
